// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhkjwlamjbdbaaygmjvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inloa2p3bGFtamJkYmFheWdtanZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNzA3MzUsImV4cCI6MjA1OTg0NjczNX0.XCc1YQS4muwNyzIoBDnh6ZkWhTeDvbURHkkx8XxmeU4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);